# Generated by Django 3.1.7 on 2021-04-01 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=20)),
                ('lastName', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='QuoteList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quoteNumber', models.CharField(max_length=10)),
                ('createdDate', models.CharField(max_length=15)),
                ('expectedDate', models.CharField(max_length=15)),
                ('customer', models.CharField(max_length=30)),
                ('salesperson', models.CharField(max_length=30)),
                ('company', models.CharField(max_length=30)),
                ('total', models.CharField(max_length=15)),
                ('status', models.BooleanField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quoteNumber', models.CharField(max_length=10)),
                ('partGroupCode', models.CharField(max_length=20)),
                ('partModelNumber', models.CharField(max_length=30)),
                ('partNumber', models.CharField(max_length=20)),
                ('partDescription', models.CharField(max_length=100)),
                ('partCost', models.CharField(max_length=20)),
                ('partPrice', models.CharField(max_length=20)),
                ('partQtyOnHand', models.IntegerField()),
                ('partQtyCommitted', models.IntegerField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoiceNumber', models.CharField(max_length=10)),
                ('customer', models.CharField(max_length=30)),
                ('createdDate', models.CharField(max_length=15)),
                ('dueDate', models.CharField(max_length=15)),
                ('totalDue', models.CharField(max_length=15)),
                ('status', models.BooleanField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
    ]
