# Generated by Django 3.1.7 on 2021-04-12 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='QuoteList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quoteNumber', models.CharField(max_length=100)),
                ('createdDate', models.CharField(max_length=100)),
                ('expectedDate', models.CharField(max_length=100)),
                ('customer', models.CharField(max_length=100)),
                ('salesperson', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('total', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=20)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partQuoteNumber', models.CharField(max_length=100)),
                ('partModelNumber', models.CharField(max_length=100)),
                ('partNumber', models.CharField(max_length=100)),
                ('partDescription', models.CharField(max_length=100)),
                ('partCost', models.CharField(max_length=100)),
                ('partPrice', models.CharField(max_length=100)),
                ('partQtyOnHand', models.CharField(max_length=100)),
                ('partQtyCommitted', models.CharField(max_length=100)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
        migrations.CreateModel(
            name='invoicePart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partInvoiceNumber', models.CharField(max_length=100)),
                ('itemCode', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('quantity', models.CharField(max_length=100)),
                ('unitPrice', models.CharField(max_length=100)),
                ('totalPrice', models.CharField(max_length=100)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoiceNumber', models.CharField(max_length=100)),
                ('customer', models.CharField(max_length=100)),
                ('createdDate', models.CharField(max_length=100)),
                ('dueDate', models.CharField(max_length=100)),
                ('totalDue', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=20)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
        migrations.CreateModel(
            name='FileInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileName', models.CharField(max_length=100)),
                ('fileData', models.FileField(upload_to='media/excel')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
        migrations.CreateModel(
            name='EmailInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PDF', models.FileField(upload_to='media/pdf/')),
                ('reciepients', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=500)),
                ('now', models.BooleanField()),
                ('later', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
    ]
