# Generated by Django 3.1.7 on 2021-04-03 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210401_1808'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='part',
            name='partGroupCode',
        ),
        migrations.AlterField(
            model_name='part',
            name='partQuoteNumber',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='quotelist',
            name='quoteNumber',
            field=models.CharField(max_length=20),
        ),
    ]
