# Generated by Django 3.1.7 on 2021-04-13 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210413_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailinfo',
            name='fileName',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
