# Generated by Django 3.1.7 on 2021-04-03 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210403_1155'),
    ]

    operations = [
        migrations.CreateModel(
            name='invoiceParts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partInvoiceNumber', models.CharField(max_length=20)),
                ('itemCode', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('unitPrice', models.FloatField(max_length=200)),
                ('totalPrice', models.FloatField(max_length=200)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
    ]
