# Generated by Django 3.1.7 on 2021-04-13 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210413_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailinfo',
            name='date',
            field=models.CharField(default='', max_length=100),
        ),
    ]
