# Generated by Django 3.1.7 on 2021-04-16 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_emailinfo_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default=None, upload_to='media/faces/% Y/% m/% d/'),
        ),
    ]
