# Generated by Django 3.1.7 on 2021-04-03 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210403_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicelist',
            name='totalDue',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='part',
            name='partCost',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='part',
            name='partPrice',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='quotelist',
            name='total',
            field=models.CharField(max_length=200),
        ),
    ]
