# Generated by Django 3.1.7 on 2021-04-09 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_fileinformation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileinformation',
            name='fileData',
            field=models.FileField(upload_to='media'),
        ),
    ]
