# Generated by Django 3.1.7 on 2021-04-09 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20210409_1140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileinformation',
            name='createdDate',
        ),
    ]
