# Generated by Django 3.1.7 on 2021-04-16 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20210416_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='/Users/iridium/Desktop/InvoiceApp/backendmedia/faces/default.png', upload_to='media/faces/%Y/%m/%d/'),
        ),
    ]
