# Generated by Django 3.1.7 on 2021-04-10 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20210409_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicelist',
            name='status',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='quotelist',
            name='status',
            field=models.CharField(max_length=20),
        ),
    ]
