# Generated by Django 3.1.7 on 2021-04-11 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20210410_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileinformation',
            name='fileData',
            field=models.FileField(upload_to='media/excel'),
        ),
    ]
