# Generated by Django 3.1.7 on 2021-04-16 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20210416_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailinfo',
            name='PDF',
            field=models.FileField(upload_to='pdf/'),
        ),
        migrations.AlterField(
            model_name='fileinformation',
            name='fileData',
            field=models.FileField(upload_to='excel/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(upload_to='faces/%Y/%m/%d/'),
        ),
    ]
