# Generated by Django 3.1.7 on 2021-04-16 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20210416_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='faces/default.png', upload_to='faces/%Y/%m/%d/'),
        ),
    ]
