# Generated by Django 3.1.7 on 2021-04-18 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_auto_20210418_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokenmake',
            name='createdDate',
            field=models.IntegerField(default=1618765320),
        ),
        migrations.AlterField(
            model_name='tokenmake',
            name='expiryDate',
            field=models.IntegerField(default=1618767120),
        ),
        migrations.AlterField(
            model_name='tokenmake',
            name='salt',
            field=models.CharField(default=b'plS4QoZFC4+FlptLIzky', max_length=500),
        ),
    ]
